fieldLayouts:
  7c44993a-d632-4bd5-b393-98350394ced8:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 762c7b39-6c09-49ee-8724-5d948dc18eb0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: cc69948b-a124-4c17-a64d-b519bf69f5c6 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9af9a273-5d56-4cfa-bfc6-d614b8949b35
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 25267ece-be52-4f83-a131-3c7a9e1b7318
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: cf9ba132-fcad-4b8c-b751-f8f46acea212 # Sidebar Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5bcb79f-8fa0-401a-a824-90159963c140
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ef70b6a7-9da3-4ffd-b6a3-33407f08a79b # Sidebar Head
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f90ca81-2f37-41b1-84c8-8a523f4460d7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 961c4e37-3a41-4b10-8ec3-6a16adb32128 # Sidebar Accordion
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa0b5737-b186-4da7-97c6-507d9292f922
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ee5c98ed-bfa0-436e-b575-a89a085760b5 # Second Sidebar Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 057fb658-9d40-45f9-8c43-381f67454a44
            userCondition: null
            warning: null
            width: 100
        name: Sidebar
        uid: 2ebe1f2a-ebce-4568-9500-279c122e31eb
        userCondition: null
handle: aboutModernBody
hasTitleField: false
name: 'About Modern Body'
section: 32622215-2664-4d65-84fb-c1a3d9939bdd # About Modern Body
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
