fieldLayouts:
  953881ca-74ca-44ab-bd2e-18db643c5916:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6769fa03-cebf-4f7c-a794-e714b2d6e469
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 68962412-698f-411d-a320-ca893137e690 # Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93fdcf4e-c540-437c-b173-b51576637d3e
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 454881f7-2966-4610-9b6e-0f4522a850a9
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6887f96e-ee16-4b11-9a20-45e7c13aeda4 # FAQs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 54208912-dd5f-47c6-8386-06a378fe1aeb
            userCondition: null
            warning: null
            width: 100
        name: 'Q & A'
        uid: 65dda3d0-4a1e-4372-83a0-84c04e517ad9
        userCondition: null
handle: faq
hasTitleField: false
name: FAQ
section: 831a1862-ae47-4961-b2a4-ddc9c451e096 # FAQ
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
