fieldLayouts:
  abdfec67-80f8-4142-9344-94cb880124a1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9121f0f4-c29a-4085-af84-e633b5d10a1a # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eaad81ed-80fc-4bd8-9ed2-2be67a53a263
            userCondition: null
            warning: null
            width: 100
        name: Title
        uid: 7d0a0656-9f3c-4e9b-ba45-f83f9fe64588
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a601171e-78df-434c-a102-c99fc4fd4d16
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e89c1ecc-9442-423f-ab32-6b3d2de27eac # Hero Logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 13f78985-4582-4b46-b492-b5ebaa1b06c5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c422089c-49f0-4d9a-9b30-dca485b14661 # Hero Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa74d5b3-02e6-46a6-8923-6359f4b09584
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 43c4b11f-16f2-4fb5-8984-7701e5e667d0 # Hero Tagline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a6b508ae-0777-43bb-8c76-349b6e5f9d2d
            userCondition: null
            warning: null
            width: 100
        name: Hero
        uid: 2d0d1b17-a520-4545-966f-1803340257ff
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 0abc2601-eb4e-47a7-bb20-6358900e5ed0 # About Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b08a1ff9-6a59-4db8-a3d3-3238e2d3f259
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e86c3ea3-5a1e-4917-a91a-cee28bdf3ca3 # About Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27276731-a4f4-473c-b717-91323b551195
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f4af40b0-3ee1-4b65-bfe3-fcf6e67c3c75 # About Signature
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db0782ff-6d5c-4e98-a3de-3edd77af1e38
            userCondition: null
            warning: null
            width: 100
        name: About
        uid: a1cdc246-92d0-4bfb-a116-f13ae06af18c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 96f6e380-8739-4368-a5b3-042e778befe7 # Company Head
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b42e343d-ecef-4068-be0c-f3ce5e8af293
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ca38367d-589e-4287-bdc0-29124c535643 # Company Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c22f5db8-4a4f-444c-ba85-73b204ee07c3
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e21c3150-347c-44cc-9e2e-64f9899bb194 # Company CTA
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4d6d3134-2c39-411c-b944-cf85fbfb6fc2
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f1dbd402-7281-4d1a-a2dc-3753d5a44df9 # Company Bullets
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: faed5c3b-08a8-4dab-b757-dfec96396b0c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0d0100be-ea79-4a84-b7ba-2a406203ef77 # Company Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 885fd775-dbd5-4220-9945-0915f084e71c
            userCondition: null
            warning: null
            width: 100
        name: Company
        uid: 97bbabec-30cc-4e6a-bfc8-de83f9f92c42
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 34d91206-bdc7-4cac-b810-e54fa52a8f98 # Products Head
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: caf3997b-7aad-4519-8b07-dd907f9347ad
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bc2faaee-59b6-4f7a-a9a5-36f7a19cbb14 # Products List
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a84bdb2-1323-4bb0-b567-0c8a25e46ca3
            userCondition: null
            warning: null
            width: 100
        name: Products
        uid: d0af2513-0711-44c3-bb47-978bbdb53479
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5d6e6468-5ba1-4d69-9cc9-61ae8d7dec0c # Testimonial Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a557efa5-b841-4b57-8323-63024fcdca77
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bfc66a87-43b5-45fb-992a-27586fcff3e4 # Testimonials Head
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 14059b5b-0236-46c6-b632-6dd9a1cb6cb7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d7efe282-0770-409c-b80d-98a2d44f3231 # Testimonials List
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2facf07c-652e-4320-b523-61fe741a6051
            userCondition: null
            warning: null
            width: 100
        name: Testimonials
        uid: 03bb47bb-21bf-45e6-9cc9-085519ec25c3
        userCondition: null
handle: home
hasTitleField: false
name: Home
section: c249f4db-294d-44b8-ba21-a84bc989d17a # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
