columnSuffix: null
contentColumnType: string
fieldGroup: 07dede5f-e375-4ca2-9622-0adde621a5c3 # Home
handle: homeCompanyCta
instructions: null
name: 'Company CTA'
searchable: false
settings:
  allowCustomText: true
  allowTarget: true
  autoNoReferrer: true
  customTextMaxLength: 0
  customTextRequired: false
  defaultLinkName: asset
  defaultText: ''
  enableAllLinkTypes: false
  enableAriaLabel: false
  enableElementCache: false
  enableTitle: false
  typeSettings:
    asset:
      allowCrossSiteLink: false
      allowCustomQuery: false
      enabled: false
      sources: '*'
    category:
      allowCrossSiteLink: false
      allowCustomQuery: false
      enabled: false
      sources: '*'
    custom:
      allowAliases: false
      disableValidation: false
      enabled: false
    email:
      allowAliases: false
      disableValidation: false
      enabled: false
    entry:
      allowCrossSiteLink: false
      allowCustomQuery: false
      enabled: true
      sources: '*'
    site:
      enabled: false
      sites: '*'
    tel:
      allowAliases: false
      disableValidation: false
      enabled: false
    url:
      allowAliases: false
      disableValidation: false
      enabled: true
    user:
      allowCrossSiteLink: false
      allowCustomQuery: false
      enabled: false
      sources: '*'
translationKeyFormat: null
translationMethod: none
type: lenz\linkfield\fields\LinkField
